apiVersion: v1
kind: Service
metadata:
  name: drone-server
spec:
  ports:
  - name: drone-server
    port: 80
    targetPort: 80
  selector:
    app: drone-server
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  labels:
    app: drone-server
spec:
  selector:
    matchLabels:
      app: drone-server
      tier: drone-server
  strategy:
    #type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: drone-server
        tier: drone-server
    spec:
      containers:
      - image: drone/drone:1
        name: drone-server
        env:
        - name: DRONE_DEBUG
          value: "true"
        - name: DRONE_ADMIN
          value: "rbekker87"
        - name: DRONE_USER_CREATE
          value: "username:rbekker87,admin:true"
        - name: DRONE_SERVER_PORT
          value: ":80"
        - name: DRONE_DATABASE_DRIVER
          #value: sqlite3
          value: "postgres"
          # https://docs.drone.io/installation/reference/drone-database-driver/
        - name: DRONE_DATABASE_DATASOURCE
          #value: /data/database.sqlite
          value: "postgres://postgres:QRRgxWTzaSPSvWMk@postgres:5432/postgres?sslmode=disable"
        - name: DRONE_GIT_ALWAYS_AUTH
          value: "false"
        - name: DRONE_GITEA_SERVER
          value: "http://gitea.localhost:8000"
        - name: DRONE_RPC_SECRET
          value: "secret"
        - name: DRONE_SERVER_HOST
          value: "drone.localhost:8000"
        - name: DRONE_HOST
          value: "http://drone-server:80"
        - name: DRONE_SERVER_PROTO
          value: "http"
        - name: DRONE_TLS_AUTOCERT
          value: "false"
        - name: DRONE_AGENTS_ENABLED
          value: "true"
        - name: DRONE_GITEA_CLIENT_ID
          value: "afb7eb33-742b-46fa-a29b-5bd3da1d9005"
        - name: DRONE_GITEA_CLIENT_SECRET
          value: "V4FXCE06yaC044BbYGCkoVOqb8o5bmZoXMc0ckS_I6w="
        ports:
        - containerPort: 80
          name: drone-server
